services:
  - type: web
    name: notevault
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notevault-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: notevault-db
    databaseName: notevault
    plan: starter
